---
title: "20191112_Descriptive"
author: "Gaotong LIU"
date: "11/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse) ## Data Manipulaion
library(corrplot) ## Correlation plot

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

## Load and tidy data
```{r}
### rename and select variables
happy = 
  read_csv("data/final_data.csv") %>% 
  rename("country" = country_name,
          "happiness_score" = life_ladder,
         "gdp" = log_gdp_per_capita,
         "life_expectance" = healthy_life_expectancy_at_birth,
         "freedom" = freedom_to_make_life_choices,
         "corruption" = perceptions_of_corruption) %>% 
  pivot_longer(gdp:corruption,
               names_to = "factors",
               values_to = "value") %>% 
  select(-c(long, lat)) %>% 
  unique()

## Creat continent variable
Asia = 
  c("Israel", "United Arab Emirates", "Singapore", "Thailand", "Taiwan Province of China",
                                   "Qatar", "Saudi Arabia", "Kuwait", "Bahrain", "Malaysia", "Uzbekistan", "Japan",
                                   "South Korea", "Turkmenistan", "Kazakhstan", "Turkey", "Hong Kong S.A.R., China", "Philippines",
                                   "Jordan", "China", "Pakistan", "Indonesia", "Azerbaijan", "Lebanon", "Vietnam",
                                   "Tajikistan", "Bhutan", "Kyrgyzstan", "Nepal", "Mongolia", "Palestinian Territories",
                                   "Iran", "Bangladesh", "Myanmar", "Iraq", "Sri Lanka", "Armenia", "India", "Georgia",
                                   "Cambodia", "Afghanistan", "Yemen", "Syria")

Europe = 
  c("Norway", "Denmark", "Iceland", "Switzerland", "Finland",
                                   "Netherlands", "Sweden", "Austria", "Ireland", "Germany",
                                   "Belgium", "Luxembourg", "United Kingdom", "Czech Republic",
                                   "Malta", "France", "Spain", "Slovakia", "Poland", "Italy",
                                   "Russia", "Lithuania", "Latvia", "Moldova", "Romania",
                                   "Slovenia", "North Cyprus", "Cyprus", "Estonia", "Belarus",
                                   "Serbia", "Hungary", "Croatia", "Kosovo", "Montenegro",
                                   "Greece", "Portugal", "Bosnia and Herzegovina", "Macedonia",
                                   "Bulgaria", "Albania", "Ukraine")

North_America = 
  c("Canada", "Costa Rica", "United States", "Mexico",  
                                   "Panama","Trinidad and Tobago", "El Salvador", "Belize", "Guatemala",
                                   "Jamaica", "Nicaragua", "Dominican Republic", "Honduras",
                                   "Haiti")

Sorth_America =  
  c("Chile", "Brazil", "Argentina", "Uruguay",
                                   "Colombia", "Ecuador", "Bolivia", "Peru",
                                   "Paraguay", "Venezuela")

Australia = 
  c("New Zealand", "Australia")

happy = happy %>% 
  mutate(continent = case_when(
    country %in% Asia ~ "Asia",
    country %in% Europe ~ "Europe",
    country %in% North_America ~ "North America",
    country %in% Sorth_America ~ "South America",
    country %in% Australia ~ "Australia",
    TRUE ~ as.character("Africa")
  ))

## May need transformation ? for MLR?
happy_transform =
  read_csv("data/final_data.csv") %>% 
  rename("country" = country_name,
          "happiness_score" = life_ladder,
         "gdp" = log_gdp_per_capita,
         "life_expectancy" = healthy_life_expectancy_at_birth,
         "freedom" = freedom_to_make_life_choices,
         "corruption" = perceptions_of_corruption) %>% 
  mutate(log_gdp =  log(gdp),
         log_life_expectancy = log(life_expectancy)) %>% 
  select(-c(long, lat, gdp, life_expectancy)) %>% 
  pivot_longer(social_support:log_life_expectancy,
               names_to = "factors",
               values_to = "value") %>%
  unique()

```

