---
title: "20191130_MLR"
author: "Gaotong LIU"
date: "11/30/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
library(tidyverse) ## Data Manipulaion

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

##  Load data
```{r load data and develop}
happy = read_csv("data/final_data_all_country.csv") %>% 
  rename("country" = country_name,
          "happiness_score" = life_ladder,
         "gdp" = log_gdp_per_capita,
         "life_expectance" = healthy_life_expectancy_at_birth,
         "freedom" = freedom_to_make_life_choices,
         "corruption" = perceptions_of_corruption) %>%
  mutate(o_gdp = exp(gdp),
         develop = ifelse(o_gdp > 25000, "developed", "developing")) %>% 
  select(-X1) %>% 
  filter(year > 2006) %>% 
  na.omit()
```


```{r continent}
## Creat continent variable
Asia = 
  c("Israel", "United Arab Emirates", "Singapore", "Thailand", "Taiwan Province of China",
                                   "Qatar", "Saudi Arabia", "Kuwait", "Bahrain", "Malaysia", "Uzbekistan", "Japan",
                                   "South Korea", "Turkmenistan", "Kazakhstan", "Turkey", "Hong Kong S.A.R., China", "Philippines",
                                   "Jordan", "China", "Pakistan", "Indonesia", "Azerbaijan", "Lebanon", "Vietnam",
                                   "Tajikistan", "Bhutan", "Kyrgyzstan", "Nepal", "Mongolia", "Palestinian Territories",
                                   "Iran", "Bangladesh", "Myanmar", "Iraq", "Sri Lanka", "Armenia", "India", "Georgia",
                                   "Cambodia", "Afghanistan", "Yemen", "Syria")

Europe = 
  c("Norway", "Denmark", "Iceland", "Switzerland", "Finland",
                                   "Netherlands", "Sweden", "Austria", "Ireland", "Germany",
                                   "Belgium", "Luxembourg", "United Kingdom", "Czech Republic",
                                   "Malta", "France", "Spain", "Slovakia", "Poland", "Italy",
                                   "Russia", "Lithuania", "Latvia", "Moldova", "Romania",
                                   "Slovenia", "North Cyprus", "Cyprus", "Estonia", "Belarus",
                                   "Serbia", "Hungary", "Croatia", "Kosovo", "Montenegro",
                                   "Greece", "Portugal", "Bosnia and Herzegovina", "Macedonia",
                                   "Bulgaria", "Albania", "Ukraine")

North_America = 
  c("Canada", "Costa Rica", "United States", "Mexico",  
                                   "Panama","Trinidad and Tobago", "El Salvador", "Belize", "Guatemala",
                                   "Jamaica", "Nicaragua", "Dominican Republic", "Honduras",
                                   "Haiti")

Sorth_America =  
  c("Chile", "Brazil", "Argentina", "Uruguay",
                                   "Colombia", "Ecuador", "Bolivia", "Peru",
                                   "Paraguay", "Venezuela")

Australia = 
  c("New Zealand", "Australia")

happy = happy %>% 
  mutate(continent = case_when(
    country %in% Asia ~ "Asia",
    country %in% Europe ~ "Europe",
    country %in% North_America ~ "North America",
    country %in% Sorth_America ~ "South America",
    country %in% Australia ~ "Australia",
    TRUE ~ as.character("Africa")
  ))
```

```{r scale}
## Standardaization
happy_standard = happy %>% 
  mutate(s_gdp = scale(gdp),
         s_social_support = scale(social_support),
         s_life_expectance = scale(life_expectance),
         s_freedom = scale(freedom),
         s_positive_affect = scale(positive_affect),
         s_negative_affect = scale(negative_affect),
         s_generosity  = scale(generosity),
         s_corruption  = scale(corruption)) %>%
  select(-c(gdp:o_gdp)) 
```
########################### Final Regression ##################
```{r}
data =  happy %>% 
  mutate(develop = as.factor(develop),
         continent = as.factor(continent)) %>%
  select(-c(country, year, o_gdp))
fit4 = lm(happiness_score~ 
            freedom + 
            negative_affect + 
            generosity + 
            life_expectance + 
            positive_affect + 
            corruption*develop + 
            social_support*develop, data = data)
summary(fit4)
```
###############################################################


```{r MLR}
data =  happy %>% 
  mutate(develop = as.factor(develop),
         continent = as.factor(continent),
         develop = relevel(develop, ref = "developing")) %>%
  select(-c(country, year, o_gdp))

data =  happy %>% 
  mutate(develop = as.factor(develop),
         continent = as.factor(continent)) %>%
  select(-c(country, year, o_gdp))
## Full fit r = 0.7384  without continent,gdp
fit = lm(happiness_score~. ,data = data %>% select(-c(continent,gdp)))
summary(fit)
##########freedom, negative_affect, generosity not significant

## Fit without continent, gdp, freedom, negative_affect, generosity
fit1 = lm(happiness_score~. ,data = data %>% select(-c(continent,gdp, freedom, negative_affect, generosity)))
summary(fit1)

## Fit with interactin
fit2 = lm(happiness_score~ 
            social_support*develop +  
            life_expectance*develop + 
            positive_affect*develop + 
            corruption*develop, data = data)
summary(fit2)

fit3 = lm(happiness_score~ 
            social_support*develop +  
            life_expectance*develop + 
            positive_affect + 
            corruption*develop, data = data)
summary(fit3)


```



```{r}
## Full fit with interaction
fit1 = lm(happiness_score~ gdp*develop + 
            social_support*develop +  
            life_expectance*develop + 
            freedom*develop + 
            positive_affect*develop + 
            negative_affect*develop + 
            generosity*develop + 
            corruption*develop + 
            continent*develop, data = data)
summary(fit1)

## Fit without develop, continent r = 0.7509
data = data %>% select(-c(continent, develop))
fit2 = lm(happiness_score~. ,data = data)
summary(fit2)
##  Fit without  gdp, continen
fit3 = lm(happiness_score~. ,data = data)
summary(fit3)
## Fit without gdp  r = 0.7715
data =  happy %>% 
  mutate(develop = as.factor(develop),
         continent = as.factor(continent)) %>% 
  select(-c(country, year, o_gdp, gdp))

fit3 = lm(happiness_score~. ,data = data)
summary(fit3)
## Fit without gdp, with intereaction
fit4 = lm(happiness_score~ 
            social_support*develop +  
            life_expectance*develop + 
            freedom*develop + 
            positive_affect*develop + 
            negative_affect*develop + 
            generosity*develop + 
            corruption*develop + 
            continent*develop, data = data)
summary(fit4)

fit5 = lm(happiness_score~ 
            social_support*develop +  
            life_expectance*develop + 
            freedom*develop + 
            positive_affect*develop + 
            negative_affect*develop + 
            generosity*develop + 
            corruption*develop, data = data)
summary(fit5)
## Model  selection
anova(fit, fit3)
anova(fit, fit2)
anova(fit, fit1)
anova(fit)
```
