---
title: "***About us***"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
editor_options: 
  chunk_output_type: console
---
<style type = "text/css">
body{ /* Normal */
    font-size: 14px;
    color: black;
}
h1.title {
font-size: 38px;
color: teal;
}
h2{ /* Header 2 */
font-size: 28px;
color: teal;
}
h3{ /* Header 3 */
font-size: 18px;
color: teal;
}
</style>

# Yuqi Miao

# Ruoyuan Qian

I am focusing on the data exploration and association map. The project gives me a chance to analysis data from real world and helps me have a deep sense in plotly and shiny! 

- [Here](https://ruoyuanqian.github.io) is my website!

# Gaotong Liu

# Shuyi Shen
I try to add gif and write some parts of report. The project gives me a chance to learn something new and get a sense of group coorperation.

If you want to know more about me, [here](https://ss-kathy.github.io/) is my personal website.

# Yuao Yang

I concern on the correlation analysis in developing and developed country, description of analysis and the screencast.
After finishing the report, I believe that MONEY can make me happy more!!!

- If you want to know me more, please click [here](https://yuaoyang.github.io/)

- If you want to chat with me, please click [here](noway.html)


