---
title: "map gif"
author: "Shuyi SHEN"
date: "11/16/2019"
output: html_document
---

```{r}
library(plotly)
library(shiny)
library(tidyverse)
library(rworldmap)
library(arsenal)
library(leaflet)
library(rworldmap) 
library(countrycode) 
library(viridis)

global_happy_year <- function(i){
  happy_yeari = happy %>% 
    filter(year == i)
  p <- plot_geo(happy_yeari) %>%
  add_trace(
    z = ~life_ladder, color = ~life_ladder, colors = 'Blues',
    text = ~label, locations = ~code, marker = list(line = l)
  ) %>%
  colorbar(title = 'Happiness index') %>%
  layout(
    title = paste(as.character(i), "Global Happiness Index"),
    geo = g
  )
  return(p)
}

happy = read_csv("data/final_data.csv") %>% 
  janitor::clean_names() %>% 
  select(-long,-lat) %>% 
  unique %>% 
  mutate(label = str_c("<b>Happiness: ", round(life_ladder,2), 
                      "</b><br>Country : ", country_name,
                      sep = ""),
        code = countrycode(country_name, 'country.name', 'iso3c'),
        code = replace_na(code,"XKX"))

l <- list(color = toRGB("grey"), width = 0.5)

g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'Mercator')
)

```



```{r}
library(magick)
library(animation)
library(rbokeh)
library(htmlwidgets)
library(mapview)
library(webshot)
library(processx)
library(listviewer)
library(gridExtra)


saveWidget(global_happy_year(2011),file = "m2011.html")
saveWidget(global_happy_year(2016),file = "m2016.html")
saveWidget(global_happy_year(2017),file = "m2017.html")
saveWidget(global_happy_year(2018),file = "m2018.html")

webshot::install_phantomjs()
webshot(url = "m2011.html",file = "data/m2011.jpg",vwidth = 990,
  vheight = 750, delay = 0.5)
webshot(url = "m2016.html",file = "data/m2016.jpg",vwidth = 992,
  vheight = 744, delay =0.5 )
webshot(url = "m2017.html",file = "data/m2017.jpg",vwidth = 992,
  vheight = 744, delay = 0.5)
webshot(url = "m2018.html",file = "data/m2018.jpg",vwidth = 990,
  vheight = 750, delay = 0.5)


list.files(path = "data/",pattern = "*.jpg",full.names = T) %>% 
  map(image_read) %>% 
  image_join() %>% 
  image_animate(fps=2) 
```

