---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: menu
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(plotly)
library(shiny)
library(tidyverse)
library(rworldmap)
library(arsenal)
library(leaflet)
library(rworldmap) 
library(countrycode)  # Gets country code 
library(viridis)
```


```{r}
## data manipulation

happy = read_csv("data/final_data_all_country.csv") %>% 
  janitor::clean_names() %>% 
  unique %>% 
  mutate(label = str_c("<b>Happiness: ", round(life_ladder,2), 
                      "</b><br>Country : ", country_name,
                      sep = ""),
        code = countrycode(country_name, 'country.name', 'iso3c'),## match code
        code = replace_na(code,"XKX"))


location = read_csv("data/concap.csv") %>% 
  janitor::clean_names() 

happy_location_raw = left_join(happy, location, by = "country_name")

 list <-which(rowSums(is.na(happy_location_raw %>% 
                              select(capital_latitude))) > 0)
  data_all_na <- happy_location_raw[list,] 
 
  happy_location_lost =  
 happy_location_raw[list,] %>% 
   mutate(capital_latitude = case_when(
    country_name == "Congo (Brazzaville)" ~ -4.267778,
    country_name == "Ivory Coast" ~ 6.85,
    country_name == "Gambia" ~ 13.466667,
    country_name == "North Cyprus" ~ 35.183333,
    country_name == "Palestinian Territories" ~ 31.516667,
    country_name == "Taiwan Province of China"~ 25.066667,
    country_name == "Somaliland region"~ 9.55,
    country_name == "Congo (Kinshasa)"~ -4.316667,
    country_name == "Hong Kong S.A.R. of China"~ 114.10000
    ),
    capital_longitude = case_when(
    country_name == "Congo (Brazzaville)" ~ 15.291944,
    country_name == "Ivory Coast" ~ 5.3,
    country_name == "Gambia" ~ -16.6,
    country_name == "North Cyprus" ~ 33.366667,
    country_name == "Palestinian Territories" ~ 34.45,
    country_name == "Taiwan Province of China"~ 121.516667,
    country_name == "Somaliland region"~ 44.05,
    country_name == "Congo (Kinshasa)"~ 15.316667,
    country_name == "Hong Kong S.A.R. of China"~ 22.20000)
    ) 
  

    
happy_location = 
bind_rows(happy_location_raw,happy_location_lost) %>% 
  drop_na(capital_latitude,capital_longitude)

 list <-which(rowSums(is.na(happy_location %>% 
                              select(capital_latitude))) > 0)
  data_all_na <- happy_location[list,]

## basic settings
# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)

# specify map projection/options
g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'Mercator')
)


```

Sidebar {.sidebar}
=======================================================================

```{r}
## Create an input widget
years = happy_location %>% distinct(year) %>% pull()
variable = names(happy_location)[5:14]

# year: selectInput widget
selectInput(
  "year_choice", ## naming the input chunk
  label = h3("Select year"), 
  choices = years, selected = "2007")## default option

# variable: selectInput widget
selectInput(
  "variable_choice", ## naming the input chunk
  label = h3("Select a predictor"), 
  choices = variable, selected = "2007")## default option

```



Dashboard
======================================================================
Row
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({ 
  global_happy_compare <- function(i,variable){
  happy_yeari_value = happy_location %>% 
    filter(year == i) %>% 
    select(variable,everything())
  happy_yeari_value %>%
  plot_geo(marker = list(color = toRGB("purple"),
                       #opacity = 0.5,    #用了整个地图会一起透明
                       #size = 0.5,
                       line = list(color = toRGB("purple"),
                                   width = 0.1))) %>%  
  add_trace(
    z = ~life_ladder, color = ~life_ladder, colors = 'Blues',
    text = ~label,locations = ~code, marker = list(line = l)
  ) %>%
    add_markers(x = ~capital_longitude,
              y = ~capital_latitude,
              sizes = c(.1, 1), #改了没变化，不知道怎么用
              size = ~happy_yeari_value[[1]]^3,
              hoverinfo = "text",
              text = ~paste("<b>Happiness:" , round(life_ladder,2),
                            '</b><br>country: ', country_name,
                            '</b><br>',variable,': ', round(happy_yeari_value[[1]],2)
                            ) ### how to specify the labels, what format?
              ) %>%
  layout(geo = g) %>% 
  colorbar(title = 'Happiness index')
  }
  
  global_happy_compare(input[["year_choice"]],input[["variable_choice"]])
  
})
```

Row
-----------------------------------------------------------------------
### Chart B

```{r}
renderPlotly({
    global_happy_rank <- function(i,variable){
    happy_yeari_value = happy_location %>% 
      filter(year == i) %>% 
      select(variable,everything())
    happy_yeari_value %>%
    mutate(rank = min_rank(-.[[1]])) %>% 
    filter(rank <= 15) %>% 
    mutate(country_name =
             fct_reorder(country_name,-.[[1]])) %>% 
    plot_ly(
    x = ~country_name,
    y = ~.[[1]],
    color = ~country_name,
    type = "bar")
  }

  global_happy_rank(input[["year_choice"]],input[["variable_choice"]])
})
```

### Chart C

```{r}
renderPlotly({
    global_happy_rank <- function(i,variable){
    happy_yeari_value = happy_location %>% 
      filter(year == i) %>% 
      select(variable,everything())
    happy_yeari_value %>%
    mutate(rank = min_rank(-.[[1]])) %>% 
    filter(rank <= 15) %>% 
    mutate(country_name =
             fct_reorder(country_name,-.[[1]])) %>% 
    plot_ly(
    x = ~country_name,
    y = ~.[[1]],
    color = ~country_name,
    type = "bar")
  }

  global_happy_rank(input[["year_choice"]],"life_ladder")
})
```





