---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: menu
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(shiny)
library(tidyverse)
library(rworldmap)
library(arsenal)
library(leaflet)
library(rworldmap) 
library(countrycode)  # Gets country code 
library(viridis)

## data manipulation

happy = read_csv("data/final_data_all_country.csv") %>% 
  janitor::clean_names() %>% 
  unique %>% 
  mutate(label = str_c("<b>Happiness: ", round(life_ladder,2), 
                      "</b><br>Country : ", country_name,
                      sep = ""),
        code = countrycode(country_name, 'country.name', 'iso3c'),## match code
        code = replace_na(code,"XKX"))


location = read_csv("data/concap.csv") %>% 
  janitor::clean_names() 

happy_location_raw = left_join(happy, location, by = "country_name")

 list <-which(rowSums(is.na(happy_location_raw %>% 
                              select(capital_latitude))) > 0)
  data_all_na <- happy_location_raw[list,] 
 
  happy_location_lost =  
 happy_location_raw[list,] %>% 
   mutate(capital_latitude = case_when(
    country_name == "Congo (Brazzaville)" ~ -4.267778,
    country_name == "Ivory Coast" ~ 6.85,
    country_name == "Gambia" ~ 13.466667,
    country_name == "North Cyprus" ~ 35.183333,
    country_name == "Palestinian Territories" ~ 31.516667,
    country_name == "Taiwan Province of China"~ 25.066667,
    country_name == "Somaliland region"~ 9.55,
    country_name == "Congo (Kinshasa)"~ -4.316667,
    country_name == "Hong Kong S.A.R. of China"~ 114.10000
    ),
    capital_longitude = case_when(
    country_name == "Congo (Brazzaville)" ~ 15.291944,
    country_name == "Ivory Coast" ~ 5.3,
    country_name == "Gambia" ~ -16.6,
    country_name == "North Cyprus" ~ 33.366667,
    country_name == "Palestinian Territories" ~ 34.45,
    country_name == "Taiwan Province of China"~ 121.516667,
    country_name == "Somaliland region"~ 44.05,
    country_name == "Congo (Kinshasa)"~ 15.316667,
    country_name == "Hong Kong S.A.R. of China"~ 22.20000)
    ) 
  

    
happy_location = 
bind_rows(happy_location_raw,happy_location_lost) %>% 
  drop_na(capital_latitude,capital_longitude) %>% 
  rename("country" = country_name,
          "happiness_score" = life_ladder,
          "gdp" = log_gdp_per_capita,
          "life_expectance" = healthy_life_expectancy_at_birth,
          "freedom" = freedom_to_make_life_choices,
          "corruption" = perceptions_of_corruption) 

 list <-which(rowSums(is.na(happy_location %>% 
                              select(capital_latitude))) > 0)
  data_all_na <- happy_location[list,]

## basic settings
# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)

# specify map projection/options
g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'Mercator')
)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
## Create an input widget
years = happy_location %>% distinct(year) %>% pull()
variable = names(happy_location)[4:11]

# year: selectInput widget
selectInput(
  "year_choice", ## naming the input chunk
  label = h3("Select year"), 
  choices = years, selected = "2007")## default option

# variable: selectInput widget
selectInput(
  "variable_choice", ## naming the input chunk
  label = h3("Select a predictor"), 
  choices = variable, selected = "2007")## default option

```



Column {data-width=650}
-----------------------------------------------------------------------
### Association map between hapiness and chosen variable

```{r}
renderPlotly({ 
  global_happy_points <- function(i,variable){
 happy_yeari_value = happy_location %>% 
    filter(year == i) %>% 
    select(variable,everything())
  
  
gaotong = happy_yeari_value %>% 
          drop_na(variable) %>% 
          pull(variable)
  
cut_point = 
  happy_yeari_value %>% 
    mutate(
    cut_point = round(quantile(gaotong)[4],3)) %>% 
  distinct(cut_point) %>% 
  pull(cut_point)

max = 
  happy_yeari_value %>% 
    mutate(
    max = round(max(gaotong),3)) %>% 
  distinct(max) %>% 
  pull(max)
    
    
min = 
  happy_yeari_value %>% 
    mutate(
    min = round(min(gaotong),3)) %>% 
  distinct(min) %>% 
  pull(min)
    

happy_yeari_value %>% 
  drop_na(variable) %>% 
  mutate(
    q = cut(gaotong,             
            breaks = c(min,cut_point,max),
            labels = c("other","top25%"),
            include.lowest = T,
            ordered = T
            )) %>% 
  plot_geo(
    marker = ~list(line = list(width = 0))
    ) %>%  
  add_trace(
    z = ~happiness_score, color = ~happiness_score,
    text = ~label, locations = ~code, marker = list(line = l)
  ) %>%
   add_markers(
    x = ~capital_longitude,
    y= ~capital_latitude, 
   color = ~q,
   sizes = c(.1, 1),
   size = ~gaotong^3,
   text = ~paste('country: ', country,
                  '</b><br>',variable,': ', 
                  round(gaotong,3))
  ) %>%
  layout(geo = g) %>% 
  colorbar(title = 'Happiness index')  }
  
  global_happy_points(input[["year_choice"]],input[["variable_choice"]])
  
})
```

Column {data-width=450}
-----------------------------------------------------------------------

### Top 15 happiest country and chosen variable

```{r}
renderPlotly({
  
    global_happy_rank <- function(i,variable){
      ay <- list(
              tickfont = list(color = "red"),
              overlaying = "y",
              side = "right",
              title = "happiness score"
            )
      happy_yeari_value = happy_location %>% 
        filter(year == i) %>% 
        select(variable,everything()) %>% 
        mutate(rank = min_rank(-happiness_score)) %>% 
        filter(rank <= 15) %>% 
        mutate(country =
                 fct_reorder(country,happiness_score))## is it because the data is untransmitted?
     p = happy_yeari_value %>% 
       plot_ly(
          x = ~country,
          y = ~.[[1]],
          type = "scatter",
          name = "Chosen variable"
       ) %>% 
        add_lines(
          x = ~country,
          y = ~happiness_score,
          name = "happiness_score",
          yaxis = "y2"
      ) %>% 
        layout(
    title = "Comparision plot",yaxis = list(title = variable), yaxis2 = ay,legend = list(x = 100, y = -0.5)
  )
     return(p)
  }

  global_happy_rank(input[["year_choice"]],input[["variable_choice"]])
})
```

### Simple linear regression between chosen variable and happiness score.

```{r}
renderPrint({
  happy_location %>% 
        filter(year == input[["year_choice"]]) %>% 
        select(input[["variable_choice"]],everything()) %>%
     lm(happiness_score~.[[1]],data = .) %>% 
     summary() %>% 
     broom::tidy() %>% 
     filter(term == ".[[1]]")
})

#renderPlotly({
#    global_happy_rank <- function(i,variable){
#    happy_yeari_value = happy_location %>% 
#      filter(year == i) %>% 
#      select(variable,everything())
#    happy_yeari_value %>%
#    mutate(rank = min_rank(-.[[1]])) %>% 
#    filter(rank <= 15) %>% 
#    mutate(country_name =
#             fct_reorder(country,-.[[1]])) %>% 
#    plot_ly(
#    x = ~country,
#    y = ~.[[1]],
#    color = ~country,
#    type = "bar")
#  }
#
#  global_happy_rank(input[["year_choice"]],"happiness_score")
#})
```





