---
title: "describiton"
author: "YuaoYang"
date: "2019/11/17"
output: github_document
---

```{r}
library(tidyverse)
library(corrplot) 
knitr::opts_chunk$set(
  fig.width = 12,
  fig.asp = 1,
  out.width = "100%"
)
theme_set(theme_bw() + theme(legend.position = "right"))


```
# manipulate the data
```{r}
data = read_csv("data/final_data_all_country.csv") %>%
  select(country_name:negative_affect) %>%
  unique() %>%
  mutate(gdp = exp(log_gdp_per_capita)) %>%# in the original data, they use log get the result, i try to transfer in the real way
  mutate( category = ifelse(gdp > 25000, "developed", "developing")) # actually there is no speicific cretiria to distinguish the developed and developing country.
```

```{r}
data  %>%
  mutate(category = factor(category, levels  = c("developed", "developing"))) %>%
  group_by(year, category) %>% 
  summarise(year_mean_score = mean(life_ladder)) %>% 
  drop_na(category)%>%
  ggplot(aes(x = year, y = year_mean_score, color = category)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +  
  facet_grid(. ~ category)
```

```{r}
data %>%
  group_by(year, category) %>% 
  ggplot(aes(x = year, y = life_ladder, group = year))+ geom_boxplot() + facet_grid(.~category)+ scale_x_continuous(
    breaks = c(2011, 2012, 2013,2014,2015,2016,2017,2018))

```

```{r}
data %>%
  group_by(year, category) %>%
  drop_na(category)%>%
  ggplot(aes(x = life_ladder, y = log_gdp_per_capita)) +
  geom_point() +
  geom_smooth(method = lm, color = "red") +
  facet_grid(year ~ category)
```