---
title: "description_final"
author: "YuaoYang"
date: "2019/11/30"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse) ## Data Manipulaion
library(corrplot) ## Correlation plot
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 1,
  out.width = "100%",
  echo = FALSE,
  message = FALSE)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))


```

## Load and tidy data
```{r}
### rename and select variables
happy = 
  read_csv("data/final_data_all_country.csv") %>% 
   rename("country" = country_name,
          "happiness_score" = life_ladder,
         "gdp" = log_gdp_per_capita,
         "life_expectance" = healthy_life_expectancy_at_birth,
         "freedom" = freedom_to_make_life_choices,
         "corruption" = perceptions_of_corruption)  %>% 
  unique() %>% 
  mutate(o_gdp = exp(gdp)) %>%# in the original data, they use log get the result, i try to transfer in the real way
  mutate(develop = ifelse(o_gdp > 25000, "developed", "developing")) # actually there is no speicific cretiria to distinguish the developed and developing country.
```

```{r}
## Creat continent variable
Asia = 
  c("Israel", "United Arab Emirates", "Singapore", "Thailand", "Taiwan Province of China",
                                   "Qatar", "Saudi Arabia", "Kuwait", "Bahrain", "Malaysia", "Uzbekistan", "Japan",
                                   "South Korea", "Turkmenistan", "Kazakhstan", "Turkey", "Hong Kong S.A.R., China", "Philippines",
                                   "Jordan", "China", "Pakistan", "Indonesia", "Azerbaijan", "Lebanon", "Vietnam",
                                   "Tajikistan", "Bhutan", "Kyrgyzstan", "Nepal", "Mongolia", "Palestinian Territories",
                                   "Iran", "Bangladesh", "Myanmar", "Iraq", "Sri Lanka", "Armenia", "India", "Georgia",
                                   "Cambodia", "Afghanistan", "Yemen", "Syria")

Europe = 
  c("Norway", "Denmark", "Iceland", "Switzerland", "Finland",
                                   "Netherlands", "Sweden", "Austria", "Ireland", "Germany",
                                   "Belgium", "Luxembourg", "United Kingdom", "Czech Republic",
                                   "Malta", "France", "Spain", "Slovakia", "Poland", "Italy",
                                   "Russia", "Lithuania", "Latvia", "Moldova", "Romania",
                                   "Slovenia", "North Cyprus", "Cyprus", "Estonia", "Belarus",
                                   "Serbia", "Hungary", "Croatia", "Kosovo", "Montenegro",
                                   "Greece", "Portugal", "Bosnia and Herzegovina", "Macedonia",
                                   "Bulgaria", "Albania", "Ukraine")

North_America = 
  c("Canada", "Costa Rica", "United States", "Mexico",  
                                   "Panama","Trinidad and Tobago", "El Salvador", "Belize", "Guatemala",
                                   "Jamaica", "Nicaragua", "Dominican Republic", "Honduras",
                                   "Haiti")

Sorth_America =  
  c("Chile", "Brazil", "Argentina", "Uruguay",
                                   "Colombia", "Ecuador", "Bolivia", "Peru",
                                   "Paraguay", "Venezuela")

Australia = 
  c("New Zealand", "Australia")

happy = happy %>% 
  mutate(continent = case_when(
    country %in% Asia ~ "Asia",
    country %in% Europe ~ "Europe",
    country %in% North_America ~ "North America",
    country %in% Sorth_America ~ "South America",
    country %in% Australia ~ "Australia",
    TRUE ~ as.character("Africa")
  ))
```


```{r}
## Standardaization
happy_standard = happy %>% 
  mutate(s_gdp = scale(gdp),
         s_social_support = scale(social_support),
         s_life_expectance = scale(life_expectance),
         s_freedom = scale(freedom),
         s_positive_affect = scale(positive_affect),
         s_negative_affect = scale(negative_affect),
         s_generosity  = scale(generosity),
         s_corruption  = scale(corruption)) %>%
  select(-c(gdp:corruption), -o_gdp)
```

### Part 1 
### Mean Happiness score of all countries: worldwide
```{r}
plot1 = happy %>% 
  filter(year>2006) %>%
  group_by(year) %>% 
  summarise(year_mean_score = mean(happiness_score)) %>% 
  ggplot(aes(x = year, y = year_mean_score)) +
  geom_path() +
  labs(title = "happiness: 2007-2018 worldwide") +scale_x_continuous(
    breaks = c(2007,2008,2009,2010,2011, 2012, 2013,2014,2015,2016,2017,2018))

plot2 = happy %>% 
  filter(year>2006)%>%
  group_by(year, continent) %>% 
  summarise(year_mean_score = mean(happiness_score)) %>% 
  ggplot(aes(x = year, y = year_mean_score, color = continent)) +
  geom_point() +
  geom_line() +
  geom_smooth(method = lm, size  = 0.5, 
              se = FALSE, color = "red") +  
  facet_grid(. ~ continent) +
  labs(title = "happiness: 2007-2018 region")

plot3 = happy %>% 
  filter(year > 2006) %>%
  drop_na(develop) %>%
  group_by(year, develop) %>% 
  summarise(year_mean_score = mean(happiness_score)) %>% 
  ggplot(aes(x = year, y = year_mean_score, color = year)) +
  geom_point() +
  geom_line() +
  geom_smooth(method = lm, size  = 0.5, 
              se = FALSE, color = "red") +  
  facet_grid(. ~ develop) +
  labs(title = "happiness: 2007-2018 develop")

plot1/plot2/plot3

```

### Part 2
```{r}
par(mfcol = c(1, 2))
happy_standard %>% 
  filter(year>2006)%>%
  pivot_longer(s_gdp:s_corruption,
               names_to = "standard_factors",
               values_to = "standard_value") %>% 
  ggplot(aes(x = happiness_score, y = standard_value,
             color  = standard_factors)) +
  geom_point() +
  geom_boxplot() +  
  geom_smooth(method = lm, color = "red") +
  facet_grid(. ~ standard_factors) +
  labs(title = "correlation:2007-2018 worldwide")

happy_standard %>% 
  drop_na() %>%
   filter(year>2006)%>%
  select(-c(X1,country, year, continent, develop)) %>% 
  cor() %>%
  corrplot.mixed(title = "2007-2018 Wordwide",
                 tl.cex = .7, tl.pos = "lt",
                  mar=c(0,0,1,0))

```

### Part 3
```{r}

par(mfcol = c(2, 2))
happy_standard %>% 
  drop_na() %>%
   filter(year>2006)%>%
  filter(continent == "Australia") %>% 
  select(-c(X1,country, year, continent, develop)) %>% 
  cor() %>%
  corrplot.mixed(title = "2007-2018 Australia",
                 tl.cex = .7, tl.pos = "lt",
                  mar=c(0,0,1,0))

happy_standard %>% 
  drop_na() %>%
   filter(year>2006)%>%
  filter(continent %in% c("Europe", "North America", "South America"))  %>% 
  select(-c(X1,country, year, continent, develop)) %>% 
  cor() %>%
  corrplot.mixed(title = "2007-2018 Europe, North America, South America",
                 tl.cex = .7, tl.pos = "lt",
                  mar=c(0,0,1,0))

happy_standard %>% 
  drop_na() %>%
   filter(year>2006)%>%
 filter(continent %in% c("Africa", "Asia")) %>% 
  select(-c(X1,country, year, continent, develop)) %>% 
  cor() %>%
  corrplot.mixed(title = "2007-2018 Africa, Asia",
                 tl.cex = .7, tl.pos = "lt",
                  mar=c(0,0,1,0))

```
### Part 4
```{r developing}
par(mfcol = c(1, 2))
happy_standard %>% 
  drop_na() %>%
   filter(year>2006)%>%
  filter(develop == "developing") %>% 
  select(-c(X1, country, year, continent, develop)) %>% 
  cor() %>%
  corrplot.mixed(title = "2007-2018 developing",
                 tl.cex = .7, tl.pos = "lt",
                  mar=c(0,0,1,0))

happy_standard %>% 
  drop_na() %>%
   filter(year>2006)%>%
  filter(develop == "developed") %>% 
  select(-c(X1,country, year, continent, develop)) %>% 
  cor() %>%
  corrplot.mixed(title = "2007-2018 developed",
                 tl.cex = .7, tl.pos = "lt",
                  mar=c(0,0,1,0))
```
